package com.lubin.bean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TAKE_STOCK_EPC_COLLECT".
 */
@Entity
public class TakeStockEpcCollect implements java.io.Serializable {

    @Id
    private Long id;
    private String taskId;
    private String epc;
    private Boolean isUpload;

    @Generated
    public TakeStockEpcCollect() {
    }

    public TakeStockEpcCollect(Long id) {
        this.id = id;
    }

    @Generated
    public TakeStockEpcCollect(Long id, String taskId, String epc, Boolean isUpload) {
        this.id = id;
        this.taskId = taskId;
        this.epc = epc;
        this.isUpload = isUpload;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTaskId() {
        return taskId;
    }

    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    public String getEpc() {
        return epc;
    }

    public void setEpc(String epc) {
        this.epc = epc;
    }

    public Boolean getIsUpload() {
        return isUpload;
    }

    public void setIsUpload(Boolean isUpload) {
        this.isUpload = isUpload;
    }

}
