package com.lubin.bean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TAKE_STOCK_SKU_COLLECT".
 */
@Entity
public class TakeStockSkuCollect implements java.io.Serializable {

    @Id
    private Long id;
    private String taskId;
    private String barcode;
    private java.util.Date date;
    private Integer num;
    private Boolean isUpload;

    @Generated
    public TakeStockSkuCollect() {
    }

    public TakeStockSkuCollect(Long id) {
        this.id = id;
    }

    @Generated
    public TakeStockSkuCollect(Long id, String taskId, String barcode, java.util.Date date, Integer num, Boolean isUpload) {
        this.id = id;
        this.taskId = taskId;
        this.barcode = barcode;
        this.date = date;
        this.num = num;
        this.isUpload = isUpload;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTaskId() {
        return taskId;
    }

    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    public String getBarcode() {
        return barcode;
    }

    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Integer getNum() {
        return num;
    }

    public void setNum(Integer num) {
        this.num = num;
    }

    public Boolean getIsUpload() {
        return isUpload;
    }

    public void setIsUpload(Boolean isUpload) {
        this.isUpload = isUpload;
    }

}
