package com.lubin.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lubin.bean.OutBoundOrder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "OUT_BOUND_ORDER".
*/
public class OutBoundOrderDao extends AbstractDao<OutBoundOrder, Long> {

    public static final String TABLENAME = "OUT_BOUND_ORDER";

    /**
     * Properties of entity OutBoundOrder.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property OrderId = new Property(1, String.class, "orderId", false, "ORDER_ID");
        public final static Property Code = new Property(2, String.class, "code", false, "CODE");
        public final static Property Status = new Property(3, String.class, "status", false, "STATUS");
        public final static Property ToWarehouseName = new Property(4, String.class, "toWarehouseName", false, "TO_WAREHOUSE_NAME");
        public final static Property OperateQty = new Property(5, Integer.class, "operateQty", false, "OPERATE_QTY");
        public final static Property Qty = new Property(6, Integer.class, "qty", false, "QTY");
        public final static Property CreateTime = new Property(7, java.util.Date.class, "createTime", false, "CREATE_TIME");
        public final static Property IsCreate = new Property(8, Boolean.class, "isCreate", false, "IS_CREATE");
    }

    private DaoSession daoSession;


    public OutBoundOrderDao(DaoConfig config) {
        super(config);
    }
    
    public OutBoundOrderDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"OUT_BOUND_ORDER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ORDER_ID\" TEXT," + // 1: orderId
                "\"CODE\" TEXT," + // 2: code
                "\"STATUS\" TEXT," + // 3: status
                "\"TO_WAREHOUSE_NAME\" TEXT," + // 4: toWarehouseName
                "\"OPERATE_QTY\" INTEGER," + // 5: operateQty
                "\"QTY\" INTEGER," + // 6: qty
                "\"CREATE_TIME\" INTEGER," + // 7: createTime
                "\"IS_CREATE\" INTEGER);"); // 8: isCreate
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"OUT_BOUND_ORDER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, OutBoundOrder entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String orderId = entity.getOrderId();
        if (orderId != null) {
            stmt.bindString(2, orderId);
        }
 
        String code = entity.getCode();
        if (code != null) {
            stmt.bindString(3, code);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(4, status);
        }
 
        String toWarehouseName = entity.getToWarehouseName();
        if (toWarehouseName != null) {
            stmt.bindString(5, toWarehouseName);
        }
 
        Integer operateQty = entity.getOperateQty();
        if (operateQty != null) {
            stmt.bindLong(6, operateQty);
        }
 
        Integer qty = entity.getQty();
        if (qty != null) {
            stmt.bindLong(7, qty);
        }
 
        java.util.Date createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindLong(8, createTime.getTime());
        }
 
        Boolean isCreate = entity.getIsCreate();
        if (isCreate != null) {
            stmt.bindLong(9, isCreate ? 1L: 0L);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, OutBoundOrder entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String orderId = entity.getOrderId();
        if (orderId != null) {
            stmt.bindString(2, orderId);
        }
 
        String code = entity.getCode();
        if (code != null) {
            stmt.bindString(3, code);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(4, status);
        }
 
        String toWarehouseName = entity.getToWarehouseName();
        if (toWarehouseName != null) {
            stmt.bindString(5, toWarehouseName);
        }
 
        Integer operateQty = entity.getOperateQty();
        if (operateQty != null) {
            stmt.bindLong(6, operateQty);
        }
 
        Integer qty = entity.getQty();
        if (qty != null) {
            stmt.bindLong(7, qty);
        }
 
        java.util.Date createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindLong(8, createTime.getTime());
        }
 
        Boolean isCreate = entity.getIsCreate();
        if (isCreate != null) {
            stmt.bindLong(9, isCreate ? 1L: 0L);
        }
    }

    @Override
    protected final void attachEntity(OutBoundOrder entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public OutBoundOrder readEntity(Cursor cursor, int offset) {
        OutBoundOrder entity = new OutBoundOrder( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // orderId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // code
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // status
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // toWarehouseName
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // operateQty
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // qty
            cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)), // createTime
            cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0 // isCreate
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, OutBoundOrder entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setOrderId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setStatus(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setToWarehouseName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setOperateQty(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setQty(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setCreateTime(cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)));
        entity.setIsCreate(cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(OutBoundOrder entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(OutBoundOrder entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(OutBoundOrder entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
