package com.lubin.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.lubin.bean.CheckTask;

import com.lubin.bean.EPC;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EPC".
*/
public class EPCDao extends AbstractDao<EPC, Long> {

    public static final String TABLENAME = "EPC";

    /**
     * Properties of entity EPC.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Tid = new Property(1, String.class, "tid", false, "TID");
        public final static Property Epc = new Property(2, String.class, "epc", false, "EPC");
        public final static Property IsUploading = new Property(3, Boolean.class, "isUploading", false, "IS_UPLOADING");
        public final static Property CheckTaskId = new Property(4, Long.class, "checkTaskId", false, "CHECK_TASK_ID");
    };

    private DaoSession daoSession;

    private Query<EPC> checkTask_EPCsQuery;

    public EPCDao(DaoConfig config) {
        super(config);
    }
    
    public EPCDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EPC\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"TID\" TEXT," + // 1: tid
                "\"EPC\" TEXT," + // 2: epc
                "\"IS_UPLOADING\" INTEGER," + // 3: isUploading
                "\"CHECK_TASK_ID\" INTEGER);"); // 4: checkTaskId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EPC\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, EPC entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String tid = entity.getTid();
        if (tid != null) {
            stmt.bindString(2, tid);
        }
 
        String epc = entity.getEpc();
        if (epc != null) {
            stmt.bindString(3, epc);
        }
 
        Boolean isUploading = entity.getIsUploading();
        if (isUploading != null) {
            stmt.bindLong(4, isUploading ? 1L: 0L);
        }
 
        Long checkTaskId = entity.getCheckTaskId();
        if (checkTaskId != null) {
            stmt.bindLong(5, checkTaskId);
        }
    }

    @Override
    protected void attachEntity(EPC entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public EPC readEntity(Cursor cursor, int offset) {
        EPC entity = new EPC( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // tid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // epc
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0, // isUploading
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // checkTaskId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, EPC entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setEpc(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIsUploading(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
        entity.setCheckTaskId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(EPC entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(EPC entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "EPCs" to-many relationship of CheckTask. */
    public List<EPC> _queryCheckTask_EPCs(Long checkTaskId) {
        synchronized (this) {
            if (checkTask_EPCsQuery == null) {
                QueryBuilder<EPC> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.CheckTaskId.eq(null));
                checkTask_EPCsQuery = queryBuilder.build();
            }
        }
        Query<EPC> query = checkTask_EPCsQuery.forCurrentThread();
        query.setParameter(0, checkTaskId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCheckTaskDao().getAllColumns());
            builder.append(" FROM EPC T");
            builder.append(" LEFT JOIN CHECK_TASK T0 ON T.\"CHECK_TASK_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected EPC loadCurrentDeep(Cursor cursor, boolean lock) {
        EPC entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        CheckTask checkTask = loadCurrentOther(daoSession.getCheckTaskDao(), cursor, offset);
        entity.setCheckTask(checkTask);

        return entity;    
    }

    public EPC loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<EPC> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<EPC> list = new ArrayList<EPC>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<EPC> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<EPC> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
