package com.lubin.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.lubin.bean.InBoundCase;
import com.lubin.bean.InBoundDetail;
import com.lubin.bean.InBoundOrder;

import com.lubin.bean.InBoundOperate;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "IN_BOUND_OPERATE".
*/
public class InBoundOperateDao extends AbstractDao<InBoundOperate, Long> {

    public static final String TABLENAME = "IN_BOUND_OPERATE";

    /**
     * Properties of entity InBoundOperate.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Barcode = new Property(1, String.class, "barcode", false, "BARCODE");
        public final static Property Epc = new Property(2, String.class, "epc", false, "EPC");
        public final static Property DeviceId = new Property(3, String.class, "deviceId", false, "DEVICE_ID");
        public final static Property MultiBarcodeId = new Property(4, String.class, "multiBarcodeId", false, "MULTI_BARCODE_ID");
        public final static Property Qty = new Property(5, Integer.class, "qty", false, "QTY");
        public final static Property OperateQty = new Property(6, Integer.class, "operateQty", false, "OPERATE_QTY");
        public final static Property IsUpload = new Property(7, Boolean.class, "isUpload", false, "IS_UPLOAD");
        public final static Property InBoundOrderId = new Property(8, Long.class, "inBoundOrderId", false, "IN_BOUND_ORDER_ID");
        public final static Property InBoundCaseId = new Property(9, Long.class, "inBoundCaseId", false, "IN_BOUND_CASE_ID");
        public final static Property InBoundDetailId = new Property(10, Long.class, "inBoundDetailId", false, "IN_BOUND_DETAIL_ID");
    }

    private DaoSession daoSession;

    private Query<InBoundOperate> inBoundOrder_OperatesQuery;
    private Query<InBoundOperate> inBoundCase_OperatesQuery;
    private Query<InBoundOperate> inBoundDetail_OperatesQuery;

    public InBoundOperateDao(DaoConfig config) {
        super(config);
    }
    
    public InBoundOperateDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IN_BOUND_OPERATE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"BARCODE\" TEXT," + // 1: barcode
                "\"EPC\" TEXT," + // 2: epc
                "\"DEVICE_ID\" TEXT," + // 3: deviceId
                "\"MULTI_BARCODE_ID\" TEXT," + // 4: multiBarcodeId
                "\"QTY\" INTEGER," + // 5: qty
                "\"OPERATE_QTY\" INTEGER," + // 6: operateQty
                "\"IS_UPLOAD\" INTEGER," + // 7: isUpload
                "\"IN_BOUND_ORDER_ID\" INTEGER," + // 8: inBoundOrderId
                "\"IN_BOUND_CASE_ID\" INTEGER," + // 9: inBoundCaseId
                "\"IN_BOUND_DETAIL_ID\" INTEGER);"); // 10: inBoundDetailId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IN_BOUND_OPERATE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, InBoundOperate entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String barcode = entity.getBarcode();
        if (barcode != null) {
            stmt.bindString(2, barcode);
        }
 
        String epc = entity.getEpc();
        if (epc != null) {
            stmt.bindString(3, epc);
        }
 
        String deviceId = entity.getDeviceId();
        if (deviceId != null) {
            stmt.bindString(4, deviceId);
        }
 
        String multiBarcodeId = entity.getMultiBarcodeId();
        if (multiBarcodeId != null) {
            stmt.bindString(5, multiBarcodeId);
        }
 
        Integer qty = entity.getQty();
        if (qty != null) {
            stmt.bindLong(6, qty);
        }
 
        Integer operateQty = entity.getOperateQty();
        if (operateQty != null) {
            stmt.bindLong(7, operateQty);
        }
 
        Boolean isUpload = entity.getIsUpload();
        if (isUpload != null) {
            stmt.bindLong(8, isUpload ? 1L: 0L);
        }
 
        Long inBoundOrderId = entity.getInBoundOrderId();
        if (inBoundOrderId != null) {
            stmt.bindLong(9, inBoundOrderId);
        }
 
        Long inBoundCaseId = entity.getInBoundCaseId();
        if (inBoundCaseId != null) {
            stmt.bindLong(10, inBoundCaseId);
        }
 
        Long inBoundDetailId = entity.getInBoundDetailId();
        if (inBoundDetailId != null) {
            stmt.bindLong(11, inBoundDetailId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, InBoundOperate entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String barcode = entity.getBarcode();
        if (barcode != null) {
            stmt.bindString(2, barcode);
        }
 
        String epc = entity.getEpc();
        if (epc != null) {
            stmt.bindString(3, epc);
        }
 
        String deviceId = entity.getDeviceId();
        if (deviceId != null) {
            stmt.bindString(4, deviceId);
        }
 
        String multiBarcodeId = entity.getMultiBarcodeId();
        if (multiBarcodeId != null) {
            stmt.bindString(5, multiBarcodeId);
        }
 
        Integer qty = entity.getQty();
        if (qty != null) {
            stmt.bindLong(6, qty);
        }
 
        Integer operateQty = entity.getOperateQty();
        if (operateQty != null) {
            stmt.bindLong(7, operateQty);
        }
 
        Boolean isUpload = entity.getIsUpload();
        if (isUpload != null) {
            stmt.bindLong(8, isUpload ? 1L: 0L);
        }
 
        Long inBoundOrderId = entity.getInBoundOrderId();
        if (inBoundOrderId != null) {
            stmt.bindLong(9, inBoundOrderId);
        }
 
        Long inBoundCaseId = entity.getInBoundCaseId();
        if (inBoundCaseId != null) {
            stmt.bindLong(10, inBoundCaseId);
        }
 
        Long inBoundDetailId = entity.getInBoundDetailId();
        if (inBoundDetailId != null) {
            stmt.bindLong(11, inBoundDetailId);
        }
    }

    @Override
    protected final void attachEntity(InBoundOperate entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public InBoundOperate readEntity(Cursor cursor, int offset) {
        InBoundOperate entity = new InBoundOperate( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // barcode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // epc
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // deviceId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // multiBarcodeId
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // qty
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // operateQty
            cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0, // isUpload
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8), // inBoundOrderId
            cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9), // inBoundCaseId
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10) // inBoundDetailId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, InBoundOperate entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBarcode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setEpc(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDeviceId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMultiBarcodeId(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setQty(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setOperateQty(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setIsUpload(cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0);
        entity.setInBoundOrderId(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
        entity.setInBoundCaseId(cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9));
        entity.setInBoundDetailId(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(InBoundOperate entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(InBoundOperate entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(InBoundOperate entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "Operates" to-many relationship of InBoundOrder. */
    public List<InBoundOperate> _queryInBoundOrder_Operates(Long inBoundOrderId) {
        synchronized (this) {
            if (inBoundOrder_OperatesQuery == null) {
                QueryBuilder<InBoundOperate> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.InBoundOrderId.eq(null));
                inBoundOrder_OperatesQuery = queryBuilder.build();
            }
        }
        Query<InBoundOperate> query = inBoundOrder_OperatesQuery.forCurrentThread();
        query.setParameter(0, inBoundOrderId);
        return query.list();
    }

    /** Internal query to resolve the "Operates" to-many relationship of InBoundCase. */
    public List<InBoundOperate> _queryInBoundCase_Operates(Long inBoundCaseId) {
        synchronized (this) {
            if (inBoundCase_OperatesQuery == null) {
                QueryBuilder<InBoundOperate> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.InBoundCaseId.eq(null));
                inBoundCase_OperatesQuery = queryBuilder.build();
            }
        }
        Query<InBoundOperate> query = inBoundCase_OperatesQuery.forCurrentThread();
        query.setParameter(0, inBoundCaseId);
        return query.list();
    }

    /** Internal query to resolve the "Operates" to-many relationship of InBoundDetail. */
    public List<InBoundOperate> _queryInBoundDetail_Operates(Long inBoundDetailId) {
        synchronized (this) {
            if (inBoundDetail_OperatesQuery == null) {
                QueryBuilder<InBoundOperate> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.InBoundDetailId.eq(null));
                inBoundDetail_OperatesQuery = queryBuilder.build();
            }
        }
        Query<InBoundOperate> query = inBoundDetail_OperatesQuery.forCurrentThread();
        query.setParameter(0, inBoundDetailId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getInBoundOrderDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getInBoundCaseDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getInBoundDetailDao().getAllColumns());
            builder.append(" FROM IN_BOUND_OPERATE T");
            builder.append(" LEFT JOIN IN_BOUND_ORDER T0 ON T.\"IN_BOUND_ORDER_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN IN_BOUND_CASE T1 ON T.\"IN_BOUND_CASE_ID\"=T1.\"_id\"");
            builder.append(" LEFT JOIN IN_BOUND_DETAIL T2 ON T.\"IN_BOUND_DETAIL_ID\"=T2.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected InBoundOperate loadCurrentDeep(Cursor cursor, boolean lock) {
        InBoundOperate entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        InBoundOrder inBoundOrder = loadCurrentOther(daoSession.getInBoundOrderDao(), cursor, offset);
        entity.setInBoundOrder(inBoundOrder);
        offset += daoSession.getInBoundOrderDao().getAllColumns().length;

        InBoundCase inBoundCase = loadCurrentOther(daoSession.getInBoundCaseDao(), cursor, offset);
        entity.setInBoundCase(inBoundCase);
        offset += daoSession.getInBoundCaseDao().getAllColumns().length;

        InBoundDetail inBoundDetail = loadCurrentOther(daoSession.getInBoundDetailDao(), cursor, offset);
        entity.setInBoundDetail(inBoundDetail);

        return entity;    
    }

    public InBoundOperate loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<InBoundOperate> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<InBoundOperate> list = new ArrayList<InBoundOperate>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<InBoundOperate> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<InBoundOperate> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
