package com.lubin.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.lubin.bean.InBoundCase;
import com.lubin.bean.InBoundOrder;

import com.lubin.bean.InBoundDetail;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "IN_BOUND_DETAIL".
*/
public class InBoundDetailDao extends AbstractDao<InBoundDetail, Long> {

    public static final String TABLENAME = "IN_BOUND_DETAIL";

    /**
     * Properties of entity InBoundDetail.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Qty = new Property(1, Integer.class, "qty", false, "QTY");
        public final static Property Date = new Property(2, java.util.Date.class, "date", false, "DATE");
        public final static Property SkuName = new Property(3, String.class, "skuName", false, "SKU_NAME");
        public final static Property OperateQty = new Property(4, Integer.class, "operateQty", false, "OPERATE_QTY");
        public final static Property Barcode = new Property(5, String.class, "barcode", false, "BARCODE");
        public final static Property MultiBarcodeId = new Property(6, String.class, "multiBarcodeId", false, "MULTI_BARCODE_ID");
        public final static Property InBoundOrderId = new Property(7, Long.class, "inBoundOrderId", false, "IN_BOUND_ORDER_ID");
        public final static Property InBoundCaseId = new Property(8, Long.class, "inBoundCaseId", false, "IN_BOUND_CASE_ID");
    }

    private DaoSession daoSession;

    private Query<InBoundDetail> inBoundOrder_DetailsQuery;
    private Query<InBoundDetail> inBoundCase_DetailsQuery;

    public InBoundDetailDao(DaoConfig config) {
        super(config);
    }
    
    public InBoundDetailDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IN_BOUND_DETAIL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"QTY\" INTEGER," + // 1: qty
                "\"DATE\" INTEGER," + // 2: date
                "\"SKU_NAME\" TEXT," + // 3: skuName
                "\"OPERATE_QTY\" INTEGER," + // 4: operateQty
                "\"BARCODE\" TEXT," + // 5: barcode
                "\"MULTI_BARCODE_ID\" TEXT," + // 6: multiBarcodeId
                "\"IN_BOUND_ORDER_ID\" INTEGER," + // 7: inBoundOrderId
                "\"IN_BOUND_CASE_ID\" INTEGER);"); // 8: inBoundCaseId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IN_BOUND_DETAIL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, InBoundDetail entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer qty = entity.getQty();
        if (qty != null) {
            stmt.bindLong(2, qty);
        }
 
        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(3, date.getTime());
        }
 
        String skuName = entity.getSkuName();
        if (skuName != null) {
            stmt.bindString(4, skuName);
        }
 
        Integer operateQty = entity.getOperateQty();
        if (operateQty != null) {
            stmt.bindLong(5, operateQty);
        }
 
        String barcode = entity.getBarcode();
        if (barcode != null) {
            stmt.bindString(6, barcode);
        }
 
        String multiBarcodeId = entity.getMultiBarcodeId();
        if (multiBarcodeId != null) {
            stmt.bindString(7, multiBarcodeId);
        }
 
        Long inBoundOrderId = entity.getInBoundOrderId();
        if (inBoundOrderId != null) {
            stmt.bindLong(8, inBoundOrderId);
        }
 
        Long inBoundCaseId = entity.getInBoundCaseId();
        if (inBoundCaseId != null) {
            stmt.bindLong(9, inBoundCaseId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, InBoundDetail entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer qty = entity.getQty();
        if (qty != null) {
            stmt.bindLong(2, qty);
        }
 
        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(3, date.getTime());
        }
 
        String skuName = entity.getSkuName();
        if (skuName != null) {
            stmt.bindString(4, skuName);
        }
 
        Integer operateQty = entity.getOperateQty();
        if (operateQty != null) {
            stmt.bindLong(5, operateQty);
        }
 
        String barcode = entity.getBarcode();
        if (barcode != null) {
            stmt.bindString(6, barcode);
        }
 
        String multiBarcodeId = entity.getMultiBarcodeId();
        if (multiBarcodeId != null) {
            stmt.bindString(7, multiBarcodeId);
        }
 
        Long inBoundOrderId = entity.getInBoundOrderId();
        if (inBoundOrderId != null) {
            stmt.bindLong(8, inBoundOrderId);
        }
 
        Long inBoundCaseId = entity.getInBoundCaseId();
        if (inBoundCaseId != null) {
            stmt.bindLong(9, inBoundCaseId);
        }
    }

    @Override
    protected final void attachEntity(InBoundDetail entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public InBoundDetail readEntity(Cursor cursor, int offset) {
        InBoundDetail entity = new InBoundDetail( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // qty
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // date
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // skuName
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // operateQty
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // barcode
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // multiBarcodeId
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // inBoundOrderId
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8) // inBoundCaseId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, InBoundDetail entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setQty(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setDate(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setSkuName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setOperateQty(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setBarcode(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setMultiBarcodeId(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setInBoundOrderId(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setInBoundCaseId(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(InBoundDetail entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(InBoundDetail entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(InBoundDetail entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "Details" to-many relationship of InBoundOrder. */
    public List<InBoundDetail> _queryInBoundOrder_Details(Long inBoundOrderId) {
        synchronized (this) {
            if (inBoundOrder_DetailsQuery == null) {
                QueryBuilder<InBoundDetail> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.InBoundOrderId.eq(null));
                inBoundOrder_DetailsQuery = queryBuilder.build();
            }
        }
        Query<InBoundDetail> query = inBoundOrder_DetailsQuery.forCurrentThread();
        query.setParameter(0, inBoundOrderId);
        return query.list();
    }

    /** Internal query to resolve the "Details" to-many relationship of InBoundCase. */
    public List<InBoundDetail> _queryInBoundCase_Details(Long inBoundCaseId) {
        synchronized (this) {
            if (inBoundCase_DetailsQuery == null) {
                QueryBuilder<InBoundDetail> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.InBoundCaseId.eq(null));
                inBoundCase_DetailsQuery = queryBuilder.build();
            }
        }
        Query<InBoundDetail> query = inBoundCase_DetailsQuery.forCurrentThread();
        query.setParameter(0, inBoundCaseId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getInBoundOrderDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getInBoundCaseDao().getAllColumns());
            builder.append(" FROM IN_BOUND_DETAIL T");
            builder.append(" LEFT JOIN IN_BOUND_ORDER T0 ON T.\"IN_BOUND_ORDER_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN IN_BOUND_CASE T1 ON T.\"IN_BOUND_CASE_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected InBoundDetail loadCurrentDeep(Cursor cursor, boolean lock) {
        InBoundDetail entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        InBoundOrder inBoundOrder = loadCurrentOther(daoSession.getInBoundOrderDao(), cursor, offset);
        entity.setInBoundOrder(inBoundOrder);
        offset += daoSession.getInBoundOrderDao().getAllColumns().length;

        InBoundCase inBoundCase = loadCurrentOther(daoSession.getInBoundCaseDao(), cursor, offset);
        entity.setInBoundCase(inBoundCase);

        return entity;    
    }

    public InBoundDetail loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<InBoundDetail> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<InBoundDetail> list = new ArrayList<InBoundDetail>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<InBoundDetail> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<InBoundDetail> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
