package com.lubin.bean;

import org.greenrobot.greendao.annotation.*;

import java.util.List;
import com.lubin.dao.DaoSession;
import org.greenrobot.greendao.DaoException;

import com.lubin.dao.InBoundCaseDao;
import com.lubin.dao.InBoundDetailDao;
import com.lubin.dao.InBoundOperateDao;
import com.lubin.dao.InBoundOrderDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "IN_BOUND_CASE".
 */
@Entity(active = true)
public class InBoundCase {

    @Id
    private Long id;
    private Integer qty;
    private Integer operateQty;
    private String code;
    private String caseId;
    private Integer status;
    private Long inBoundOrderId;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient InBoundCaseDao myDao;

    @ToOne(joinProperty = "inBoundOrderId")
    private InBoundOrder inBoundOrder;

    @Generated
    private transient Long inBoundOrder__resolvedKey;

    @ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "inBoundCaseId")
    })
    private List<InBoundDetail> Details;

    @ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "inBoundCaseId")
    })
    private List<InBoundOperate> Operates;

    @Generated
    public InBoundCase() {
    }

    public InBoundCase(Long id) {
        this.id = id;
    }

    @Generated
    public InBoundCase(Long id, Integer qty, Integer operateQty, String code, String caseId, Integer status, Long inBoundOrderId) {
        this.id = id;
        this.qty = qty;
        this.operateQty = operateQty;
        this.code = code;
        this.caseId = caseId;
        this.status = status;
        this.inBoundOrderId = inBoundOrderId;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getInBoundCaseDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getQty() {
        return qty;
    }

    public void setQty(Integer qty) {
        this.qty = qty;
    }

    public Integer getOperateQty() {
        return operateQty;
    }

    public void setOperateQty(Integer operateQty) {
        this.operateQty = operateQty;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getCaseId() {
        return caseId;
    }

    public void setCaseId(String caseId) {
        this.caseId = caseId;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Long getInBoundOrderId() {
        return inBoundOrderId;
    }

    public void setInBoundOrderId(Long inBoundOrderId) {
        this.inBoundOrderId = inBoundOrderId;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public InBoundOrder getInBoundOrder() {
        Long __key = this.inBoundOrderId;
        if (inBoundOrder__resolvedKey == null || !inBoundOrder__resolvedKey.equals(__key)) {
            __throwIfDetached();
            InBoundOrderDao targetDao = daoSession.getInBoundOrderDao();
            InBoundOrder inBoundOrderNew = targetDao.load(__key);
            synchronized (this) {
                inBoundOrder = inBoundOrderNew;
            	inBoundOrder__resolvedKey = __key;
            }
        }
        return inBoundOrder;
    }

    @Generated
    public void setInBoundOrder(InBoundOrder inBoundOrder) {
        synchronized (this) {
            this.inBoundOrder = inBoundOrder;
            inBoundOrderId = inBoundOrder == null ? null : inBoundOrder.getId();
            inBoundOrder__resolvedKey = inBoundOrderId;
        }
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<InBoundDetail> getDetails() {
        if (Details == null) {
            __throwIfDetached();
            InBoundDetailDao targetDao = daoSession.getInBoundDetailDao();
            List<InBoundDetail> DetailsNew = targetDao._queryInBoundCase_Details(id);
            synchronized (this) {
                if(Details == null) {
                    Details = DetailsNew;
                }
            }
        }
        return Details;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetDetails() {
        Details = null;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<InBoundOperate> getOperates() {
        if (Operates == null) {
            __throwIfDetached();
            InBoundOperateDao targetDao = daoSession.getInBoundOperateDao();
            List<InBoundOperate> OperatesNew = targetDao._queryInBoundCase_Operates(id);
            synchronized (this) {
                if(Operates == null) {
                    Operates = OperatesNew;
                }
            }
        }
        return Operates;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetOperates() {
        Operates = null;
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
