package com.lubin.bean;

import org.greenrobot.greendao.annotation.*;

import java.util.List;
import com.lubin.dao.DaoSession;
import org.greenrobot.greendao.DaoException;

import com.lubin.dao.InBoundCaseDao;
import com.lubin.dao.InBoundDetailDao;
import com.lubin.dao.InBoundOperateDao;
import com.lubin.dao.InBoundOrderDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "IN_BOUND_DETAIL".
 */
@Entity(active = true)
public class InBoundDetail {

    @Id
    private Long id;
    private Integer qty;
    private java.util.Date date;
    private String skuName;
    private Integer operateQty;
    private String barcode;
    private String multiBarcodeId;
    private Long inBoundOrderId;
    private Long inBoundCaseId;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient InBoundDetailDao myDao;

    @ToOne(joinProperty = "inBoundOrderId")
    private InBoundOrder inBoundOrder;

    @Generated
    private transient Long inBoundOrder__resolvedKey;

    @ToOne(joinProperty = "inBoundCaseId")
    private InBoundCase inBoundCase;

    @Generated
    private transient Long inBoundCase__resolvedKey;

    @ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "inBoundDetailId")
    })
    private List<InBoundOperate> Operates;

    @Generated
    public InBoundDetail() {
    }

    public InBoundDetail(Long id) {
        this.id = id;
    }

    @Generated
    public InBoundDetail(Long id, Integer qty, java.util.Date date, String skuName, Integer operateQty, String barcode, String multiBarcodeId, Long inBoundOrderId, Long inBoundCaseId) {
        this.id = id;
        this.qty = qty;
        this.date = date;
        this.skuName = skuName;
        this.operateQty = operateQty;
        this.barcode = barcode;
        this.multiBarcodeId = multiBarcodeId;
        this.inBoundOrderId = inBoundOrderId;
        this.inBoundCaseId = inBoundCaseId;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getInBoundDetailDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getQty() {
        return qty;
    }

    public void setQty(Integer qty) {
        this.qty = qty;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getSkuName() {
        return skuName;
    }

    public void setSkuName(String skuName) {
        this.skuName = skuName;
    }

    public Integer getOperateQty() {
        return operateQty;
    }

    public void setOperateQty(Integer operateQty) {
        this.operateQty = operateQty;
    }

    public String getBarcode() {
        return barcode;
    }

    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    public String getMultiBarcodeId() {
        return multiBarcodeId;
    }

    public void setMultiBarcodeId(String multiBarcodeId) {
        this.multiBarcodeId = multiBarcodeId;
    }

    public Long getInBoundOrderId() {
        return inBoundOrderId;
    }

    public void setInBoundOrderId(Long inBoundOrderId) {
        this.inBoundOrderId = inBoundOrderId;
    }

    public Long getInBoundCaseId() {
        return inBoundCaseId;
    }

    public void setInBoundCaseId(Long inBoundCaseId) {
        this.inBoundCaseId = inBoundCaseId;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public InBoundOrder getInBoundOrder() {
        Long __key = this.inBoundOrderId;
        if (inBoundOrder__resolvedKey == null || !inBoundOrder__resolvedKey.equals(__key)) {
            __throwIfDetached();
            InBoundOrderDao targetDao = daoSession.getInBoundOrderDao();
            InBoundOrder inBoundOrderNew = targetDao.load(__key);
            synchronized (this) {
                inBoundOrder = inBoundOrderNew;
            	inBoundOrder__resolvedKey = __key;
            }
        }
        return inBoundOrder;
    }

    @Generated
    public void setInBoundOrder(InBoundOrder inBoundOrder) {
        synchronized (this) {
            this.inBoundOrder = inBoundOrder;
            inBoundOrderId = inBoundOrder == null ? null : inBoundOrder.getId();
            inBoundOrder__resolvedKey = inBoundOrderId;
        }
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public InBoundCase getInBoundCase() {
        Long __key = this.inBoundCaseId;
        if (inBoundCase__resolvedKey == null || !inBoundCase__resolvedKey.equals(__key)) {
            __throwIfDetached();
            InBoundCaseDao targetDao = daoSession.getInBoundCaseDao();
            InBoundCase inBoundCaseNew = targetDao.load(__key);
            synchronized (this) {
                inBoundCase = inBoundCaseNew;
            	inBoundCase__resolvedKey = __key;
            }
        }
        return inBoundCase;
    }

    @Generated
    public void setInBoundCase(InBoundCase inBoundCase) {
        synchronized (this) {
            this.inBoundCase = inBoundCase;
            inBoundCaseId = inBoundCase == null ? null : inBoundCase.getId();
            inBoundCase__resolvedKey = inBoundCaseId;
        }
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<InBoundOperate> getOperates() {
        if (Operates == null) {
            __throwIfDetached();
            InBoundOperateDao targetDao = daoSession.getInBoundOperateDao();
            List<InBoundOperate> OperatesNew = targetDao._queryInBoundDetail_Operates(id);
            synchronized (this) {
                if(Operates == null) {
                    Operates = OperatesNew;
                }
            }
        }
        return Operates;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetOperates() {
        Operates = null;
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
