package com.lubin.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lubin.bean.User;
import com.lubin.bean.CheckTask;
import com.lubin.bean.EPC;

import com.lubin.dao.UserDao;
import com.lubin.dao.CheckTaskDao;
import com.lubin.dao.EPCDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig checkTaskDaoConfig;
    private final DaoConfig ePCDaoConfig;

    private final UserDao userDao;
    private final CheckTaskDao checkTaskDao;
    private final EPCDao ePCDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        checkTaskDaoConfig = daoConfigMap.get(CheckTaskDao.class).clone();
        checkTaskDaoConfig.initIdentityScope(type);

        ePCDaoConfig = daoConfigMap.get(EPCDao.class).clone();
        ePCDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        checkTaskDao = new CheckTaskDao(checkTaskDaoConfig, this);
        ePCDao = new EPCDao(ePCDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(CheckTask.class, checkTaskDao);
        registerDao(EPC.class, ePCDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        checkTaskDaoConfig.getIdentityScope().clear();
        ePCDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public CheckTaskDao getCheckTaskDao() {
        return checkTaskDao;
    }

    public EPCDao getEPCDao() {
        return ePCDao;
    }

}
