//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.example.music.activity;

import java.util.ArrayList;
import android.content.Context;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageButton;
import android.widget.SeekBar;
import android.widget.TextView;
import com.example.activity.R.id;
import com.example.activity.R.layout;
import com.example.music.myview.DiscView;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class PlayerActivity_
    extends PlayerActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_player);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        ibList = new ArrayList<ImageButton>();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static PlayerActivity_.IntentBuilder_ intent(Context context) {
        return new PlayerActivity_.IntentBuilder_(context);
    }

    public static PlayerActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new PlayerActivity_.IntentBuilder_(fragment);
    }

    public static PlayerActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new PlayerActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        ibList.clear();
        tvCurrent = ((TextView) hasViews.findViewById(id.tv_player_current));
        discView = ((DiscView) hasViews.findViewById(id.disc_view));
        seekBar = ((SeekBar) hasViews.findViewById(id.sb_player_progress));
        tvDuration = ((TextView) hasViews.findViewById(id.tv_player_durationtime));
        Viewheader = hasViews.findViewById(id.title_view_player);
        {
            ImageButton view = ((ImageButton) hasViews.findViewById(id.ib_player_isfav));
            if (view!= null) {
                ibList.add(view);
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PlayerActivity_.this.onClick(view);
                    }

                }
                );
            }
        }
        {
            ImageButton view = ((ImageButton) hasViews.findViewById(id.ib_player_download));
            if (view!= null) {
                ibList.add(view);
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PlayerActivity_.this.onClick(view);
                    }

                }
                );
            }
        }
        {
            ImageButton view = ((ImageButton) hasViews.findViewById(id.ib_player_previous));
            if (view!= null) {
                ibList.add(view);
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PlayerActivity_.this.onClick(view);
                    }

                }
                );
            }
        }
        {
            ImageButton view = ((ImageButton) hasViews.findViewById(id.ib_player_play));
            if (view!= null) {
                ibList.add(view);
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PlayerActivity_.this.onClick(view);
                    }

                }
                );
            }
        }
        {
            ImageButton view = ((ImageButton) hasViews.findViewById(id.ib_play_next));
            if (view!= null) {
                ibList.add(view);
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PlayerActivity_.this.onClick(view);
                    }

                }
                );
            }
        }
        init();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<PlayerActivity_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, PlayerActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), PlayerActivity_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), PlayerActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

    }

}
