package com.lubin.bean;

import org.greenrobot.greendao.annotation.*;

import com.lubin.dao.DaoSession;
import org.greenrobot.greendao.DaoException;

import com.lubin.dao.TakeStockOrderDao;
import com.lubin.dao.TakeStockTaskDao;
import com.lubin.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TAKE_STOCK_TASK".
 */
@Entity(active = true)
public class TakeStockTask implements java.io.Serializable {

    @Id
    private Long id;
    private String name;
    private String warehouseCode;
    private String codeId;
    private Integer realPoint;
    private Boolean complete;
    private java.util.Date date;
    private String upperCase;
    private String lowerCase;
    private Integer mode;
    private Long userId;
    private Long orderId;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient TakeStockTaskDao myDao;

    @ToOne(joinProperty = "userId")
    private User user;

    @Generated
    private transient Long user__resolvedKey;

    @ToOne(joinProperty = "orderId")
    private TakeStockOrder takeStockOrder;

    @Generated
    private transient Long takeStockOrder__resolvedKey;

    @Generated
    public TakeStockTask() {
    }

    public TakeStockTask(Long id) {
        this.id = id;
    }

    @Generated
    public TakeStockTask(Long id, String name, String warehouseCode, String codeId, Integer realPoint, Boolean complete, java.util.Date date, String upperCase, String lowerCase, Integer mode, Long userId, Long orderId) {
        this.id = id;
        this.name = name;
        this.warehouseCode = warehouseCode;
        this.codeId = codeId;
        this.realPoint = realPoint;
        this.complete = complete;
        this.date = date;
        this.upperCase = upperCase;
        this.lowerCase = lowerCase;
        this.mode = mode;
        this.userId = userId;
        this.orderId = orderId;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getTakeStockTaskDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getWarehouseCode() {
        return warehouseCode;
    }

    public void setWarehouseCode(String warehouseCode) {
        this.warehouseCode = warehouseCode;
    }

    public String getCodeId() {
        return codeId;
    }

    public void setCodeId(String codeId) {
        this.codeId = codeId;
    }

    public Integer getRealPoint() {
        return realPoint;
    }

    public void setRealPoint(Integer realPoint) {
        this.realPoint = realPoint;
    }

    public Boolean getComplete() {
        return complete;
    }

    public void setComplete(Boolean complete) {
        this.complete = complete;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getUpperCase() {
        return upperCase;
    }

    public void setUpperCase(String upperCase) {
        this.upperCase = upperCase;
    }

    public String getLowerCase() {
        return lowerCase;
    }

    public void setLowerCase(String lowerCase) {
        this.lowerCase = lowerCase;
    }

    public Integer getMode() {
        return mode;
    }

    public void setMode(Integer mode) {
        this.mode = mode;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getOrderId() {
        return orderId;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public User getUser() {
        Long __key = this.userId;
        if (user__resolvedKey == null || !user__resolvedKey.equals(__key)) {
            __throwIfDetached();
            UserDao targetDao = daoSession.getUserDao();
            User userNew = targetDao.load(__key);
            synchronized (this) {
                user = userNew;
            	user__resolvedKey = __key;
            }
        }
        return user;
    }

    @Generated
    public void setUser(User user) {
        synchronized (this) {
            this.user = user;
            userId = user == null ? null : user.getId();
            user__resolvedKey = userId;
        }
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public TakeStockOrder getTakeStockOrder() {
        Long __key = this.orderId;
        if (takeStockOrder__resolvedKey == null || !takeStockOrder__resolvedKey.equals(__key)) {
            __throwIfDetached();
            TakeStockOrderDao targetDao = daoSession.getTakeStockOrderDao();
            TakeStockOrder takeStockOrderNew = targetDao.load(__key);
            synchronized (this) {
                takeStockOrder = takeStockOrderNew;
            	takeStockOrder__resolvedKey = __key;
            }
        }
        return takeStockOrder;
    }

    @Generated
    public void setTakeStockOrder(TakeStockOrder takeStockOrder) {
        synchronized (this) {
            this.takeStockOrder = takeStockOrder;
            orderId = takeStockOrder == null ? null : takeStockOrder.getId();
            takeStockOrder__resolvedKey = orderId;
        }
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
